/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#d8e2ff",
        tertiary: "#89ceff",
        "surface-tint": "#adc6ff",
        error: "#ffb4ab",
        "on-primary": "#002e6a",
        "surface-container-low": "#0d1c2d",
        "outline-variant": "#424754",
        "inverse-on-surface": "#233143",
        "on-error": "#690005",
        "inverse-primary": "#005ac2",
        "on-surface": "#d4e4fa",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#001e2f",
        "secondary-fixed-dim": "#d2bbff",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#c9e6ff",
        "on-secondary-fixed": "#25005a",
        "on-secondary-container": "#c9aeff",
        "on-tertiary-fixed-variant": "#004c6e",
        "tertiary-fixed-dim": "#89ceff",
        "inverse-surface": "#d4e4fa",
        outline: "#8c909f",
        "primary-container": "#4d8eff",
        "on-secondary": "#3f008e",
        "on-primary-fixed-variant": "#004395",
        "surface-dim": "#051424",
        "surface-container-highest": "#273647",
        "surface-container-lowest": "#010f1f",
        primary: "#adc6ff",
        "on-background": "#d4e4fa",
        "secondary-container": "#6001d1",
        surface: "#051424",
        "secondary-fixed": "#eaddff",
        "primary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#c2c6d6",
        "surface-variant": "#273647",
        "surface-bright": "#2c3a4c",
        "on-tertiary": "#00344d",
        "surface-container": "#122131",
        "on-primary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#5a00c6",
        background: "#051424",
        secondary: "#d2bbff",
        "on-primary-container": "#00285d",
        "surface-container-high": "#1c2b3c",
        "tertiary-container": "#009ada",
        "on-tertiary-container": "#002d43",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sm: "12px",
        "container-max": "1440px",
        md: "24px",
        base: "8px",
        xs: "4px",
        lg: "40px",
        xl: "64px",
        gutter: "24px",
      },
      fontFamily: {
        geist: ["Geist", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "1.2", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" },
        ],
      },
      keyframes: {
        scroll: {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-100%)" },
        },
      },
      animation: {
        scroll: "scroll 40s linear infinite",
      },
    },
  },
  plugins: [],
};
